package pages;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class ThuocTinhHoSoTaiLieu {
	DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy hh:ss");
	DateTimeFormatter formatNgayVanBan = DateTimeFormatter.ofPattern("dd/MM/yyyy");
	public String createdTime = myFormatObj.format(LocalDateTime.now());
	public String so_hop_dong = "HĐ2020/VT-PT" + createdTime;
	public String noi_dung_hop_dong = "Nội dung trên form Hồ sơ Tài liệu " + createdTime;
	public String ngay_ky = "08/07/2021";
	public String nguoi_ky = "Eoff Giám đốc";
	public String ngay_hieu_luc = "08/07/2021";
	public String noi_luu = "Văn phòng công ty, Khối Vận hành và Công nghệ Áp dụng";
	public String linh_vuc = "Ban CNTT";
	public String ho_so_luu_tru = "Hồ sơ Lưu trữ Form Tạo mới";
	public String filepathKySo01 = "C:\\AttachFiles\\FileKySo01.docx";
	public String y_kien_trinh = "Ý kiến trình của người soạn thảo Hợp đồng";
	public String nguoi_tao_hstl = "Eoff Chuyên viên 2";
	public String don_vi_soan_thao = "Đơn vị Upgrade";
	public String ten_nguoi_ky = "Eoff Giám đốc";
	public String ngay_tao = formatNgayVanBan.format(LocalDateTime.now());
	public String file_word_ky_so_1_trang_key_stt = "C:\\AttachFiles\\SiteDonViSql\\VB Ky so - 1 trang - Key STT.docx";
	public String file_ky_so_1_trang = "C:\\AttachFiles\\File Ky so 1 trang.doc";
	public String file_bcnb_ky_so = "C:\\AttachFiles\\PLXKV1\\File Bao cao noi bo Ky so.doc";
	public String file_bbnb_ky_so = "C:\\\\AttachFiles\\\\File Bien ban Noi bo Ky so.doc";
	public String file_ky_so_nhieu_trang = "C:\\AttachFiles\\File Ky So Nhieu Trang.doc";
	public String file_pdf_ky_so = "C:\\AttachFiles\\File PDF Ky So.pdf";
	public String file_excel_ky_so = "C:\\AttachFiles\\File Excel Ky So.xlsx";
	public String file_bbtt_ky_so = "C:\\AttachFiles\\PLXKV1\\File BBTT Ky So.doc";
	public String file_totrinh_ky_so = "C:\\AttachFiles\\PLXKV1\\File To trinh Ky so.doc";
	public String file_totrinh_khong_key_ngay_thang_nam = "C:\\AttachFiles\\SiteDonViSql\\HSTL Ky so - Khong Key Ngay Thang Nam.docx";
	public String file_totrinh_ky_so_nhieu_user = "C:\\AttachFiles\\PLXKV1\\File To trinh Ky So Nhieu User.doc";
	public String file_totrinh_tp_trinh_tgd = "C:\\AttachFiles\\PLXKV1\\File To trinh Tp trinh TGD.docx";
	public String file_totrinh_ky_so_loi = "C:\\AttachFiles\\PLXKV1\\File Ky so To trinh loi.doc";
	public String file_hop_dong_ky_so = "C:\\AttachFiles\\PLXKV1\\File HD Ky So.doc";
	public String file_hstl_ky_so_loi = "C:\\AttachFiles\\SiteDonViSql\\HSTL Ky so - File Ky so loi.doc";
	public String file_hstl_2_key_user = "C:\\AttachFiles\\SiteDonViSql\\HSTL Ky so - Key User.docx";
	public String file_hstl_2_key_user_va_stt = "C:\\AttachFiles\\SiteDonViSql\\HSTL Ky so - File Ky so 2 Key User va STT.docx";
	public String file_hstl_2_key_ky_nhay = "C:\\AttachFiles\\SiteDonViSql\\HSTL Ky so - File Ky so 2 Key Ky nhay.docx";
	public String file_hstl_ky_so_nhieu_user = "C:\\AttachFiles\\SiteDonViSql\\HSTL Ky so - Nhieu User.doc";
	public String file_hstl_2_key_stt = "C:\\AttachFiles\\SiteDonViSql\\HSTL Ky so - File Ky so 2 Key User.docx";
	public String file_hstl_khac_ky_so = "C:\\AttachFiles\\Fie Ho so Tai lieu Khac Ky so.docx";
	public String so_hop_dong_edit = "HĐ2020/VT-PT" + System.currentTimeMillis();
	public String noi_dung_hop_dong_edit = "Nội dung trên form Hồ sơ Tài liệu Edit " + createdTime;
	public String ngay_ky_edit = "20/07/2021";
	public String ngay_hieu_luc_edit = "25/07/2021";
	public String noi_luu_edit = "Văn phòng công ty, Khối Vận hành và Công nghệ Áp dụng Edit";
	public String linh_vuc_edit = "Văn phòng";
	public String ho_so_luu_tru_edit = "Hồ sơ Lưu trữ Form Edit";
	public String lanh_dao_phe_duyet_khac = "Chuyên viên 1";
	public String lanh_dao_pb = "Eoff Trưởng phòng";
	public String lanh_dao_vp = "eoff.cvp";
	public String user_phe_duyet_hstl = "Eoff Chủ tịch";
	public String lanh_dao_bgd = "Eoff Giám đốc";
	public String van_thu = "eoff.vthu";
	public String y_kien_phe_duyet_hstl = "Ý kiến phê duyệt HSTL" + createdTime;
	public String so_van_ban = "TT/2021" + System.currentTimeMillis();
	public String so_van_ban_edit = "TT/2021/Edit" + System.currentTimeMillis();
	public String trich_yeu = "Trích yếu trên form Hồ sơ Tài liệu " + createdTime;
	public String trich_yeu_edit = "Trích yếu trên form Hồ sơ Tài liệu Edit " + createdTime;
	public String ten_ho_so = "Tên Hồ sơ tài liệu Khác " + createdTime;
	public String ten_ho_so_edit = "Tên Hồ sơ tài liệu Khác Edit " + createdTime;
	public String lanh_dao_phong_lien_quan = "Eoff TPHC";
	public String lanh_dao_dong_phe_duyet = "Eoff Phó Giám đốc";
	public String lanh_dao_duyet_vb = "Eoff Giám đốc";
	

}
